---
version: '2'

tasks:
  default:
    cmds:
      - task -s --list

  serve:
    desc: "Start server to preview changes"
    cmds:
      - docker run --rm -it
        -p 4000:4000
        -e JEKYLL_GITHUB_TOKEN
        -v ${PWD}:/app
        antonmarin/github-pages:192-alpine
