name: default

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prebuild validations
      run: make lint
    - name: test build jekyll
      run: make test
