name: lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: lint with markdown-lint
      run: |
        curl -sL https://taskfile.dev/install.sh | sh && \
        task lint
