name: lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install task
      run: curl -sL https://taskfile.dev/install.sh | sh
    - name: lint with markdown-lint
      run: bin/task lint
